theme = "gruvbox_dark_transparent"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.statusline]
right = ["diagnostics", "selections", "register", "file-encoding", "position", "position-percentage"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]


[keys.normal.space]
w = ":write"
q = ":quit"
